"""changed nullable to False in Recipe in models.py

Revision ID: 4dd31b1cde84
Revises: 3a23deb41078
Create Date: 2024-04-05 12:15:31.896864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dd31b1cde84'
down_revision = '3a23deb41078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('time_to_make',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('ingredients',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('instructions',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('instructions',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('ingredients',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('time_to_make',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
