"""Had the tablename wrong should be favorite_recipes.

Revision ID: 6ca3e3b15252
Revises: 49e7752a081c
Create Date: 2024-04-16 13:50:08.516711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ca3e3b15252'
down_revision = '49e7752a081c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_favorite_recipes_recipe_id_recipes')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favorite_recipes_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favorite_categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('recipe_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='fk_favorite_categories_recipe_id_recipes'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_favorite_categories_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favorite_recipes')
    # ### end Alembic commands ###
