"""added _password_hash to User

Revision ID: 874c4cc15546
Revises: 58028a4cfe94
Create Date: 2024-04-03 13:18:02.521995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '874c4cc15546'
down_revision = '58028a4cfe94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###
