"""Added model RecipeCategory.

Revision ID: a14429cf7489
Revises: dd7b0ec8b3ef
Create Date: 2024-04-11 14:04:09.369667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a14429cf7489'
down_revision = 'dd7b0ec8b3ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_categories',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_recipe_categories_category_id_categories')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_recipe_categories_recipe_id_recipes')),
    sa.PrimaryKeyConstraint('recipe_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_categories')
    # ### end Alembic commands ###
