"""Commented out category to troubleshoot.

Revision ID: ad00eed1ac4f
Revises: 5a7be3301bf3
Create Date: 2024-04-08 13:47:25.880821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad00eed1ac4f'
down_revision = '5a7be3301bf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    op.drop_table('recipe_categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_categories',
    sa.Column('recipe_id', sa.INTEGER(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='fk_recipe_categories_category_id_categories'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='fk_recipe_categories_recipe_id_recipes'),
    sa.PrimaryKeyConstraint('recipe_id', 'category_id')
    )
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
